/** @format */

import LayoutContainer from "./LayoutContainer";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <LayoutContainer>{children}</LayoutContainer>
      </body>
    </html>
  );
}
